name: datasam2get
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python版本
  - python=3.10
  
  # 深度学习框架 (CPU版本，适用于Mac)
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio
  # 移除 pytorch-cuda，Mac使用CPU版本
  
  # 计算机视觉和图像处理
  - opencv>=4.5.0
  - pillow>=8.3.0
  - matplotlib>=3.3.0
  - seaborn>=0.11.0
  
  # 数据处理
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  
  # 工具包
  - pyyaml>=6.0
  - tqdm>=4.62.0
  
  # GUI支持 (Mac兼容版本)
  - pyqt=5
  
  # 视频处理
  - ffmpeg
  
  # 使用pip安装的包
  - pip
  - pip:
    # Web UI框架
    - streamlit>=1.25.0
    - streamlit-image-coordinates>=0.1.6
    
    # YOLO和SAM模型
    - ultralytics>=8.0.0
    
    # 视频处理
    - moviepy>=1.0.3
    
    # 模型导出和优化
    - onnx>=1.12.0
    - onnxruntime>=1.12.0
    
    # 监控和可视化
    - tensorboard>=2.8.0
    
    # 其他工具
    - uuid
    - pathlib
    
    # SAM2依赖（需要单独安装）
    # 注意: SAM2需要从GitHub手动安装 